[package]
name = "bdk-journey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
# bdk = { version = "0.29", features = ["all-keys"], optional = false}
# bdk = { version = "1.0.0-alpha.3", features = ["all-keys"] }
# bdk_file_store = { git = "https://github.com/bitcoindevkit/bdk", branch = "master"}
# bdk_esplora = { git = "https://github.com/bitcoindevkit/bdk", branch = "master", features = ["async"] }

bdk = { path = "./../bdk/crates/bdk" }
bdk_esplora = { path = "../bdk/crates/esplora", features = ["async-https"] }
bdk_file_store = { path = "../bdk/crates/file_store" }

# bdk = { git = "https://github.com/notmandatory/bdk.git", branch = "test/esplora_tests", version = "1.0.0-alpha.1", features = ["keys-bip39"]}
# bdk_esplora = { git = "https://github.com/notmandatory/bdk.git", branch = "test/esplora_tests", version = "0.3.0" }
# bdk_file_store = { git = "https://github.com/notmandatory/bdk.git", branch = "test/esplora_tests", version = "0.2.0" }
# bdk_chain = "0.6"
# bip39 = { version = "^1.0.1", optional = false }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }