[package]
name = "atomicals-electrumx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
array-bytes        = { version = "6.2" }
bitcoin = { version = "0.31", features = ["rand-std"] }
ciborium  = "0.2"
num_cpus = "1.16"
rand = { version = "0.8" }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }

tracing            = { version = "0.1" }
tracing-subscriber = { version = "0.3" }