[package]
name = "bitwai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bdk = { version = "0.29", features = ["all-keys", "sqlite"] }
dirs-next = "2"
config = "0.13"
dotenv = "0.15"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
